import numpy as np


def load_csv(file_name):
    """ Load a csv-file generated by Audio2LED.
    PARAMETER
    ---------
    file_name: str
        the path to the csv file

    RETURNS
    -------
    led_time: ndarray
        the time in seconds from the start
    led_channel_levels: ndarray
        2D array for the LED channels and frames
    """
    data = np.genfromtxt(file_name, delimiter=',', dtype=int, skip_header=1)
    led_time = data[:, 0] / 1000.
    led_channel_levels = data[:, 1:].T

    return led_time, led_channel_levels
